/* HEADER *********************************************************************************/
/*!
\file	PPForEach.h
\author Tan Jie Wei Jacky (100%)
\par    email: t.jieweijacky\@digipen.edu
\brief
	Applies a macro to every element

All Content Copyright © 2018 DigiPen (SINGAPORE) Corporation, all rights reserved.
Reproduction or disclosure of this file or its contents without the
prior written consent of DigiPen Institute of Technology is prohibited.
*/
/* HEADER END *****************************************************************************/
#ifndef _PP_FOREACH_SEQ_H_
#define _PP_FOREACH_SEQ_H_

#include "Reflection/PPUtils.h"
#include "Reflection/PPRemove.h"
#include "Reflection/PPConcat.h"
#include "Reflection/PPExtract.h"
#include "Reflection/PPPopFront.h"
#include "Reflection/PPVariadicSize.h"

/*
#define PP_FOREACH_SEQ(_ACTION_, ...) PP_CONCAT(_ACTION_, PP_EXTRACT(0, __VA_ARGS__)) PP_FOREACH_SEQ_AUX1(_ACTION_, __VA_ARGS__)
*/

#define PP_FOREACH(_ACTION_, _PARAMS_, ...)       PP_CONCAT(PP_FOREACH, PP_VARIADIC_SIZE(__VA_ARGS__)) (_ACTION_, _PARAMS_, __VA_ARGS__)


#define PP_FOREACH1(_ACTION_, _PARAMS_, _LAST_)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _LAST_)
#define PP_FOREACH2(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH1) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH3(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH2) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH4(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH3) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH5(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH4) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH6(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH5) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH7(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH6) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH8(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH7) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH9(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH8) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH10(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH9) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH11(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH10) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH12(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH11) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH13(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH12) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH14(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH13) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH15(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH14) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH16(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH15) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH17(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH16) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH18(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH17) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH19(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH18) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH20(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH19) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH21(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH20) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH22(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH21) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH23(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH22) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH24(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH23) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH25(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH24) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH26(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH25) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH27(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH26) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH28(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH27) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH29(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH28) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH30(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH29) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH31(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH30) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH32(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH31) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH33(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH32) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH34(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH33) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH35(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH34) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH36(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH35) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH37(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH36) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH38(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH37) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH39(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH38) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH40(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH39) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH41(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH40) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH42(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH41) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH43(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH42) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH44(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH43) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH45(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH44) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH46(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH45) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH47(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH46) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH48(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH47) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH49(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH48) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH50(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH49) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH51(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH50) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH52(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH51) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH53(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH52) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH54(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH53) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH55(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH54) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH56(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH55) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH57(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH56) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH58(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH57) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH59(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH58) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH60(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH59) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH61(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH60) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH62(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH61) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH63(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH62) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH64(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH63) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH65(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH64) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH66(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH65) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH67(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH66) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH68(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH67) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH69(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH68) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH70(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH69) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH71(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH70) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH72(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH71) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH73(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH72) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH74(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH73) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH75(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH74) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH76(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH75) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH77(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH76) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH78(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH77) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH79(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH78) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH80(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH79) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH81(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH80) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH82(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH81) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH83(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH82) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH84(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH83) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH85(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH84) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH86(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH85) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH87(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH86) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH88(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH87) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH89(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH88) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH90(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH89) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH91(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH90) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH92(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH91) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH93(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH92) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH94(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH93) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH95(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH94) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH96(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH95) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH97(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH96) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH98(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH97) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH99(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH98) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH100(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH99) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH101(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH100) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH102(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH101) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH103(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH102) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH104(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH103) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH105(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH104) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH106(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH105) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH107(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH106) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH108(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH107) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH109(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH108) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH110(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH109) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH111(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH110) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH112(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH111) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH113(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH112) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH114(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH113) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH115(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH114) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH116(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH115) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH117(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH116) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH118(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH117) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH119(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH118) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH120(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH119) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH121(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH120) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH122(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH121) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH123(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH122) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH124(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH123) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH125(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH124) (_ACTION_, _PARAMS_, __VA_ARGS__)


/*
#define PP_FOREACH_SEQ_AUX1(_X_, _SEQ_)     PP_CONCAT(PP_FOREACH_SEQ_AUX2, PP_POPFRONT(_SEQ_)), _X_)
#define PP_FOREACH_SEQ_AUX2(...)            PP_FOREACH_SEQ_AUX3 ((__VA_ARGS__)
#define PP_FOREACH_SEQ_AUX3(_SEQ_, _X_)     PP_FOREACH_SEQ_AUX4() (_X_, _SEQ_)
#define PP_FOREACH_SEQ_AUX20                PP_REMOVE(
#define PP_FOREACH_SEQ_AUX4()               PP_OBSTRUCT(PP_FOREACH_SEQ)
*/



#endif		// INCLUDE GUARD

