/* HEADER *********************************************************************************/
/*!
\file	PPExtract.h
\author Tan Jie Wei Jacky (100%)
\par    email: t.jieweijacky\@digipen.edu
\brief
	Extracts the nth element of a sequence

All Content Copyright © 2018 DigiPen (SINGAPORE) Corporation, all rights reserved.
Reproduction or disclosure of this file or its contents without the
prior written consent of DigiPen Institute of Technology is prohibited.
*/
/* HEADER END *****************************************************************************/
#ifndef _PP_EXTRACTFRONT_H_
#define _PP_EXTRACTFRONT_H_

#include "PP/PPUtils.h"
#include "PP/PPRemove.h"
#include "PP/PPConcat.h"


#define PP_EXTRACTFRONT(_SEQ_) PP_EXTRACT(0, _SEQ_)


#define PP_EXTRACT(_INDEX_, _SEQ_) PP_EXTRACT_AUX_3(_INDEX_,_SEQ_)
#define PP_EXTRACT_VA(_INDEX_, ...) PP_EXTRACT_VA_AUX ## _INDEX_(__VA_ARGS__)

#define PP_EXTRACT_AUX_1(_AUX_)          PP_EVAL(PP_EXTRACT_AUX_2 _AUX_)
#define PP_EXTRACT_AUX_2(_SEQ_, _X_)     (_SEQ_)
#define PP_EXTRACT_AUX_3(_INDEX_, _SEQ_) PP_EXTRACT_AUX_1((PP_EXTRACT ## _INDEX_ _SEQ_))


#define PP_EXTRACT0(_X_) _X_, 0
#define PP_EXTRACT1(_X_) PP_EXTRACT0
#define PP_EXTRACT2(_X_) PP_EXTRACT1
#define PP_EXTRACT3(_X_) PP_EXTRACT2
#define PP_EXTRACT4(_X_) PP_EXTRACT3
#define PP_EXTRACT5(_X_) PP_EXTRACT4
#define PP_EXTRACT6(_X_) PP_EXTRACT5
#define PP_EXTRACT7(_X_) PP_EXTRACT6
#define PP_EXTRACT8(_X_) PP_EXTRACT7
#define PP_EXTRACT9(_X_) PP_EXTRACT8
#define PP_EXTRACT10(_X_) PP_EXTRACT9
#define PP_EXTRACT11(_X_) PP_EXTRACT10
#define PP_EXTRACT12(_X_) PP_EXTRACT11
#define PP_EXTRACT13(_X_) PP_EXTRACT12
#define PP_EXTRACT14(_X_) PP_EXTRACT13
#define PP_EXTRACT15(_X_) PP_EXTRACT14
#define PP_EXTRACT16(_X_) PP_EXTRACT15
#define PP_EXTRACT17(_X_) PP_EXTRACT16
#define PP_EXTRACT18(_X_) PP_EXTRACT17
#define PP_EXTRACT19(_X_) PP_EXTRACT18
#define PP_EXTRACT20(_X_) PP_EXTRACT19
#define PP_EXTRACT21(_X_) PP_EXTRACT20
#define PP_EXTRACT22(_X_) PP_EXTRACT21
#define PP_EXTRACT23(_X_) PP_EXTRACT22
#define PP_EXTRACT24(_X_) PP_EXTRACT23
#define PP_EXTRACT25(_X_) PP_EXTRACT24
#define PP_EXTRACT26(_X_) PP_EXTRACT25
#define PP_EXTRACT27(_X_) PP_EXTRACT26
#define PP_EXTRACT28(_X_) PP_EXTRACT27
#define PP_EXTRACT29(_X_) PP_EXTRACT28
#define PP_EXTRACT30(_X_) PP_EXTRACT29
#define PP_EXTRACT31(_X_) PP_EXTRACT30
#define PP_EXTRACT32(_X_) PP_EXTRACT31
#define PP_EXTRACT33(_X_) PP_EXTRACT32
#define PP_EXTRACT34(_X_) PP_EXTRACT33
#define PP_EXTRACT35(_X_) PP_EXTRACT34
#define PP_EXTRACT36(_X_) PP_EXTRACT35
#define PP_EXTRACT37(_X_) PP_EXTRACT36
#define PP_EXTRACT38(_X_) PP_EXTRACT37
#define PP_EXTRACT39(_X_) PP_EXTRACT38
#define PP_EXTRACT40(_X_) PP_EXTRACT39
#define PP_EXTRACT41(_X_) PP_EXTRACT40
#define PP_EXTRACT42(_X_) PP_EXTRACT41
#define PP_EXTRACT43(_X_) PP_EXTRACT42
#define PP_EXTRACT44(_X_) PP_EXTRACT43
#define PP_EXTRACT45(_X_) PP_EXTRACT44
#define PP_EXTRACT46(_X_) PP_EXTRACT45
#define PP_EXTRACT47(_X_) PP_EXTRACT46
#define PP_EXTRACT48(_X_) PP_EXTRACT47
#define PP_EXTRACT49(_X_) PP_EXTRACT48
#define PP_EXTRACT50(_X_) PP_EXTRACT49
#define PP_EXTRACT51(_X_) PP_EXTRACT50
#define PP_EXTRACT52(_X_) PP_EXTRACT51
#define PP_EXTRACT53(_X_) PP_EXTRACT52
#define PP_EXTRACT54(_X_) PP_EXTRACT53
#define PP_EXTRACT55(_X_) PP_EXTRACT54
#define PP_EXTRACT56(_X_) PP_EXTRACT55
#define PP_EXTRACT57(_X_) PP_EXTRACT56
#define PP_EXTRACT58(_X_) PP_EXTRACT57
#define PP_EXTRACT59(_X_) PP_EXTRACT58
#define PP_EXTRACT60(_X_) PP_EXTRACT59
#define PP_EXTRACT61(_X_) PP_EXTRACT60
#define PP_EXTRACT62(_X_) PP_EXTRACT61
#define PP_EXTRACT63(_X_) PP_EXTRACT62
#define PP_EXTRACT64(_X_) PP_EXTRACT63
#define PP_EXTRACT65(_X_) PP_EXTRACT64
#define PP_EXTRACT66(_X_) PP_EXTRACT65
#define PP_EXTRACT67(_X_) PP_EXTRACT66
#define PP_EXTRACT68(_X_) PP_EXTRACT67
#define PP_EXTRACT69(_X_) PP_EXTRACT68
#define PP_EXTRACT70(_X_) PP_EXTRACT69
#define PP_EXTRACT71(_X_) PP_EXTRACT70
#define PP_EXTRACT72(_X_) PP_EXTRACT71
#define PP_EXTRACT73(_X_) PP_EXTRACT72
#define PP_EXTRACT74(_X_) PP_EXTRACT73
#define PP_EXTRACT75(_X_) PP_EXTRACT74
#define PP_EXTRACT76(_X_) PP_EXTRACT75
#define PP_EXTRACT77(_X_) PP_EXTRACT76
#define PP_EXTRACT78(_X_) PP_EXTRACT77
#define PP_EXTRACT79(_X_) PP_EXTRACT78
#define PP_EXTRACT80(_X_) PP_EXTRACT79
#define PP_EXTRACT81(_X_) PP_EXTRACT80
#define PP_EXTRACT82(_X_) PP_EXTRACT81
#define PP_EXTRACT83(_X_) PP_EXTRACT82
#define PP_EXTRACT84(_X_) PP_EXTRACT83
#define PP_EXTRACT85(_X_) PP_EXTRACT84
#define PP_EXTRACT86(_X_) PP_EXTRACT85
#define PP_EXTRACT87(_X_) PP_EXTRACT86
#define PP_EXTRACT88(_X_) PP_EXTRACT87
#define PP_EXTRACT89(_X_) PP_EXTRACT88
#define PP_EXTRACT90(_X_) PP_EXTRACT89
#define PP_EXTRACT91(_X_) PP_EXTRACT90
#define PP_EXTRACT92(_X_) PP_EXTRACT91
#define PP_EXTRACT93(_X_) PP_EXTRACT92
#define PP_EXTRACT94(_X_) PP_EXTRACT93
#define PP_EXTRACT95(_X_) PP_EXTRACT94
#define PP_EXTRACT96(_X_) PP_EXTRACT95
#define PP_EXTRACT97(_X_) PP_EXTRACT96
#define PP_EXTRACT98(_X_) PP_EXTRACT97
#define PP_EXTRACT99(_X_) PP_EXTRACT98
#define PP_EXTRACT100(_X_) PP_EXTRACT99
#define PP_EXTRACT101(_X_) PP_EXTRACT100
#define PP_EXTRACT102(_X_) PP_EXTRACT101
#define PP_EXTRACT103(_X_) PP_EXTRACT102
#define PP_EXTRACT104(_X_) PP_EXTRACT103
#define PP_EXTRACT105(_X_) PP_EXTRACT104
#define PP_EXTRACT106(_X_) PP_EXTRACT105
#define PP_EXTRACT107(_X_) PP_EXTRACT106
#define PP_EXTRACT108(_X_) PP_EXTRACT107
#define PP_EXTRACT109(_X_) PP_EXTRACT108
#define PP_EXTRACT110(_X_) PP_EXTRACT109
#define PP_EXTRACT111(_X_) PP_EXTRACT110
#define PP_EXTRACT112(_X_) PP_EXTRACT111
#define PP_EXTRACT113(_X_) PP_EXTRACT112
#define PP_EXTRACT114(_X_) PP_EXTRACT113
#define PP_EXTRACT115(_X_) PP_EXTRACT114
#define PP_EXTRACT116(_X_) PP_EXTRACT115
#define PP_EXTRACT117(_X_) PP_EXTRACT116
#define PP_EXTRACT118(_X_) PP_EXTRACT117
#define PP_EXTRACT119(_X_) PP_EXTRACT118
#define PP_EXTRACT120(_X_) PP_EXTRACT119
#define PP_EXTRACT121(_X_) PP_EXTRACT120
#define PP_EXTRACT122(_X_) PP_EXTRACT121
#define PP_EXTRACT123(_X_) PP_EXTRACT122
#define PP_EXTRACT124(_X_) PP_EXTRACT123

#define PP_EXTRACT_VA_AUX0(_1, ...) _1
#define PP_EXTRACT_VA_AUX1(_1, ...)  PP_EVAL(PP_EXTRACT_VA_AUX0)(__VA_ARGS__)
#define PP_EXTRACT_VA_AUX2(_1, ...)  PP_EVAL(PP_EXTRACT_VA_AUX1)(__VA_ARGS__)
#define PP_EXTRACT_VA_AUX3(_1, ...)  PP_EVAL(PP_EXTRACT_VA_AUX2)(__VA_ARGS__)
#define PP_EXTRACT_VA_AUX4(_1, ...)  PP_EVAL(PP_EXTRACT_VA_AUX3)(__VA_ARGS__)
#define PP_EXTRACT_VA_AUX5(_1, ...)  PP_EVAL(PP_EXTRACT_VA_AUX4)(__VA_ARGS__)
#define PP_EXTRACT_VA_AUX6(_1, ...)  PP_EVAL(PP_EXTRACT_VA_AUX5)(__VA_ARGS__)
#define PP_EXTRACT_VA_AUX7(_1, ...)  PP_EVAL(PP_EXTRACT_VA_AUX6)(__VA_ARGS__)
#define PP_EXTRACT_VA_AUX8(_1, ...)  PP_EVAL(PP_EXTRACT_VA_AUX7)(__VA_ARGS__)
#define PP_EXTRACT_VA_AUX9(_1, ...)  PP_EVAL(PP_EXTRACT_VA_AUX8)(__VA_ARGS__)
#define PP_EXTRACT_VA_AUX10(_1, ...) PP_EVAL(PP_EXTRACT_VA_AUX9)(__VA_ARGS__)
#define PP_EXTRACT_VA_AUX11(_1, ...) PP_EVAL(PP_EXTRACT_VA_AUX10)(__VA_ARGS__)
#define PP_EXTRACT_VA_AUX12(_1, ...) PP_EVAL(PP_EXTRACT_VA_AUX11)(__VA_ARGS__)
#define PP_EXTRACT_VA_AUX13(_1, ...) PP_EVAL(PP_EXTRACT_VA_AUX12)(__VA_ARGS__)
#define PP_EXTRACT_VA_AUX14(_1, ...) PP_EVAL(PP_EXTRACT_VA_AUX13)(__VA_ARGS__)
#define PP_EXTRACT_VA_AUX15(_1, ...) PP_EVAL(PP_EXTRACT_VA_AUX14)(__VA_ARGS__)
#define PP_EXTRACT_VA_AUX16(_1, ...) PP_EVAL(PP_EXTRACT_VA_AUX15)(__VA_ARGS__)
#define PP_EXTRACT_VA_AUX17(_1, ...) PP_EVAL(PP_EXTRACT_VA_AUX16)(__VA_ARGS__)
#define PP_EXTRACT_VA_AUX18(_1, ...) PP_EVAL(PP_EXTRACT_VA_AUX17)(__VA_ARGS__)
#define PP_EXTRACT_VA_AUX19(_1, ...) PP_EVAL(PP_EXTRACT_VA_AUX18)(__VA_ARGS__)



#endif		// INCLUDE GUARD

