/* HEADER *********************************************************************************/
/*!
\file	PPForEach.h
\author Tan Jie Wei Jacky (100%)
\par    email: t.jieweijacky\@digipen.edu
\brief
	Applies a macro to every element

All Content Copyright © 2018 DigiPen (SINGAPORE) Corporation, all rights reserved.
Reproduction or disclosure of this file or its contents without the
prior written consent of DigiPen Institute of Technology is prohibited.
*/
/* HEADER END *****************************************************************************/
#ifndef _PP_FOREACH_SEQ_H_
#define _PP_FOREACH_SEQ_H_

#include "PP/PPUtils.h"
#include "PP/PPRemove.h"
#include "PP/PPConcat.h"
#include "PP/PPExtract.h"
#include "PP/PPPopFront.h"
#include "PP/PPVariadicSize.h"

/*
#define PP_FOREACH_SEQ(_ACTION_, ...) PP_CONCAT(_ACTION_, PP_EXTRACT(0, __VA_ARGS__)) PP_FOREACH_SEQ_AUX1(_ACTION_, __VA_ARGS__)
*/

#define PP_FOREACH PP_FOREACH_VA
#define PP_FOREACH_VA(_ACTION_, _PARAMS_, ...)   PP_CONCAT PP_FOREACH_BLOCK() (PP_FOREACH_AUX, PP_VA_SIZE(__VA_ARGS__)) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_BLOCK() 


#define PP_FOREACH_AUX1(_ACTION_, _PARAMS_, _LAST_)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _LAST_)
#define PP_FOREACH_AUX2(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX1) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX3(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX2) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX4(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX3) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX5(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX4) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX6(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX5) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX7(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX6) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX8(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX7) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX9(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX8) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX10(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX9) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX11(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX10) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX12(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX11) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX13(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX12) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX14(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX13) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX15(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX14) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX16(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX15) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX17(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX16) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX18(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX17) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX19(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX18) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX20(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX19) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX21(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX20) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX22(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX21) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX23(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX22) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX24(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX23) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX25(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX24) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX26(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX25) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX27(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX26) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX28(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX27) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX29(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX28) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX30(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX29) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX31(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX30) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX32(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX31) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX33(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX32) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX34(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX33) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX35(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX34) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX36(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX35) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX37(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX36) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX38(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX37) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX39(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX38) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX40(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX39) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX41(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX40) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX42(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX41) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX43(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX42) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX44(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX43) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX45(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX44) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX46(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX45) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX47(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX46) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX48(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX47) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX49(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX48) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX50(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX49) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX51(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX50) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX52(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX51) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX53(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX52) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX54(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX53) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX55(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX54) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX56(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX55) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX57(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX56) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX58(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX57) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX59(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX58) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX60(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX59) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX61(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX60) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX62(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX61) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX63(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX62) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX64(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX63) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX65(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX64) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX66(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX65) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX67(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX66) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX68(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX67) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX69(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX68) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX70(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX69) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX71(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX70) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX72(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX71) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX73(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX72) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX74(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX73) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX75(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX74) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX76(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX75) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX77(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX76) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX78(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX77) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX79(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX78) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX80(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX79) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX81(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX80) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX82(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX81) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX83(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX82) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX84(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX83) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX85(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX84) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX86(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX85) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX87(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX86) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX88(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX87) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX89(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX88) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX90(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX89) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX91(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX90) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX92(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX91) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX93(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX92) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX94(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX93) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX95(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX94) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX96(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX95) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX97(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX96) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX98(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX97) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX99(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX98) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX100(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX99) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX101(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX100) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX102(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX101) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX103(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX102) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX104(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX103) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX105(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX104) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX106(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX105) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX107(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX106) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX108(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX107) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX109(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX108) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX110(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX109) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX111(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX110) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX112(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX111) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX113(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX112) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX114(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX113) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX115(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX114) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX116(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX115) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX117(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX116) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX118(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX117) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX119(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX118) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX120(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX119) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX121(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX120) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX122(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX121) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX123(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX122) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX124(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX123) (_ACTION_, _PARAMS_, __VA_ARGS__)
#define PP_FOREACH_AUX125(_ACTION_, _PARAMS_, _ELEM_, ...)  _ACTION_(PP_REMOVEBRACE _PARAMS_, _ELEM_), PP_OBSTRUCT(PP_FOREACH_AUX124) (_ACTION_, _PARAMS_, __VA_ARGS__)

/*
#define PP_FOREACH_SEQ_AUX1(_X_, _SEQ_)     PP_CONCAT(PP_FOREACH_SEQ_AUX2, PP_POPFRONT(_SEQ_)), _X_)                    
#define PP_FOREACH_SEQ_AUX2(...)            PP_FOREACH_SEQ_AUX5((__VA_ARGS__)                                           
#define PP_FOREACH_SEQ_AUX20                PP_REMOVE(                                                                  
#define PP_FOREACH_SEQ_AUX3(_SEQ_, _X_)     PP_FOREACH_SEQ_AUX4(_X_, _SEQ_)                                             
#define PP_FOREACH_SEQ_AUX4                 PP_EVAL(PP_OBSTRUCT(PP_FOREACH_SEQ_II))
#define PP_FOREACH_SEQ_AUX5(...)            PP_OBSTRUCT(PP_CONCAT)(PP_FOREACH_SEQ_AUX3, (__VA_ARGS__)) PP_FOREACH_BLOCK()

#define PP_FOREACH_SEQ_II(_ACTION_, ...) PP_CONCAT(_ACTION_, PP_EXTRACT(0, __VA_ARGS__)) PP_FOREACH_SEQ_II_AUX1(_ACTION_, __VA_ARGS__)

#define PP_FOREACH_SEQ_II_AUX1(_X_, _SEQ_)     PP_CONCAT(PP_FOREACH_SEQ_II_AUX2, PP_POPFRONT(_SEQ_)), _X_)
#define PP_FOREACH_SEQ_II_AUX2(...)            PP_FOREACH_SEQ_II_AUX5((__VA_ARGS__)
#define PP_FOREACH_SEQ_II_AUX20                PP_REMOVE(
#define PP_FOREACH_SEQ_II_AUX3(_SEQ_, _X_)     PP_FOREACH_SEQ_II_AUX4(_X_, _SEQ_)
#define PP_FOREACH_SEQ_II_AUX4                 PP_EVAL(PP_OBSTRUCT(PP_FOREACH_SEQ))
#define PP_FOREACH_SEQ_II_AUX5(...)            PP_OBSTRUCT(PP_CONCAT)(PP_FOREACH_SEQ_II_AUX3,(__VA_ARGS__)) PP_FOREACH_BLOCK()
*/


#endif		// INCLUDE GUARD

